#!/bin/bash
# Setup GFX pipeline with H.264 encoding for xrdp on Debian 13 (trixie).
#
# Configures xrdp to use the Xorg backend with the GFX graphics pipeline
# and H.264 encoding via x264 for better video performance.
#
# Run as root on the xrdp target machine (not the rustguac server).
# Requires: xrdp >= 0.10, xorgxrdp, libx264
#
# Usage: sudo bash setup-xrdp-gfx.sh
set -e

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: run as root (sudo bash $0)"
    exit 1
fi

echo "=== Checking prerequisites ==="
if ! dpkg -l xrdp >/dev/null 2>&1; then
    echo "Error: xrdp is not installed"
    exit 1
fi

XRDP_VERSION=$(dpkg -l xrdp | awk '/^ii/{print $3}')
echo "  xrdp version: $XRDP_VERSION"

if ! dpkg -l xorgxrdp >/dev/null 2>&1; then
    echo "Error: xorgxrdp is not installed. Install with: apt install xorgxrdp"
    exit 1
fi
echo "  xorgxrdp: installed"

# Install x264 if not present
if ! dpkg -l libx264-164 >/dev/null 2>&1; then
    echo ""
    echo "=== Installing libx264 ==="
    apt-get update -qq
    apt-get install -y libx264-164
fi
echo "  libx264: installed"

echo ""
echo "=== Configuring Xorg as default session ==="
if grep -q "^autorun=$" /etc/xrdp/xrdp.ini; then
    sed -i "s/^autorun=$/autorun=Xorg/" /etc/xrdp/xrdp.ini
    echo "  Set autorun=Xorg"
elif grep -q "^autorun=Xorg" /etc/xrdp/xrdp.ini; then
    echo "  Already set to Xorg"
else
    CURRENT=$(grep "^autorun=" /etc/xrdp/xrdp.ini)
    echo "  Warning: autorun is set to '$CURRENT' — not changing."
    echo "  For GFX support, set autorun=Xorg in /etc/xrdp/xrdp.ini"
fi

echo ""
echo "=== Creating GFX configuration ==="
GFX_CONF="/etc/xrdp/gfx.toml"
if [ -f "$GFX_CONF" ]; then
    cp "$GFX_CONF" "${GFX_CONF}.bak"
    echo "  Backed up existing $GFX_CONF to ${GFX_CONF}.bak"
fi

cat > "$GFX_CONF" << 'EOF'
# GFX Pipeline Configuration for xrdp
# Generated by rustguac contrib/setup-xrdp-gfx.sh
#
# H.264 encoding with x264 for best video performance.
# See: man 5 gfx.toml

[codec]
order = ["H.264", "RFX"]
h264_encoder = "x264"

[x264]
preset = "ultrafast"
tune = "zerolatency"
profile = "main"
vbv_max_bitrate = 0
vbv_buffer_size = 0
fps_num = 60
fps_den = 1
threads = 0

[x264.connection.lan]
preset = "ultrafast"
tune = "zerolatency"
vbv_max_bitrate = 0
fps_num = 60
fps_den = 1

[x264.connection.broadband_high]
preset = "ultrafast"
tune = "zerolatency"
vbv_max_bitrate = 20000
fps_num = 30
fps_den = 1
EOF
echo "  Created $GFX_CONF"

echo ""
echo "=== Restarting xrdp ==="
systemctl restart xrdp
echo "  xrdp restarted"

echo ""
echo "=== Done ==="
echo ""
echo "xrdp is now configured with:"
echo "  - Xorg backend (required for GFX pipeline)"
echo "  - H.264 encoding via x264 (60fps LAN, 30fps broadband)"
echo "  - RemoteFX as fallback codec"
echo ""
echo "In rustguac, enable 'Graphics Pipeline (GFX)' and"
echo "'Desktop Composition' on RDP address book entries"
echo "for best video performance."
